version: '3.5'

services:
  api:
    container_name: user-service
    build: .
    environment:
      DB_NAME: user_db
      DB_USER: admin
      DB_PASS: admin
      GATEWAY_PATH: http://api-gateway:5000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
    networks: 
      - qr-comer
      - default
  
  db:
    container_name: user-service-db
    image: postgres:latest
    # command: printenv
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: 
      - default
    
volumes:
  pgdata:
    driver: local

networks: 
  qr-comer:
    external:
      name: qr-comer
