version: '3.5'

services:
  api:
    container_name: user-service
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    container_name: user-service-db
    image: postgres:9.6
    environment:
      POSTGRES_HOST: dbhost
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
    driver: local
