version: '3.5'

services:
  db:
    container_name: user-service-db
    image: postgres:latest
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    # command: printenv
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
      container_name: user-service
      build: .
      environment:
        DB_NAME: user_db
        DB_USER: admin
        DB_PASS: admin
      command: /start.sh

      volumes:
        - .:/project
      ports:
        - 8000:8000
      depends_on:
        - db

volumes:
  pgdata:
    driver: local
