# Generated by Django 2.2.5 on 2019-09-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('registro', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
