# Generated by Django 2.2.6 on 2019-10-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='status_user',
            field=models.BooleanField(default=True),
        ),
    ]
