# Generated by Django 2.2.6 on 2019-10-19 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('validation', models.DateField(verbose_name='Validade')),
                ('holder_name', models.CharField(max_length=30)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
