# Generated by Django 2.2.6 on 2019-10-22 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_auto_20191021_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='profile',
            field=models.ManyToManyField(related_name='user_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_user',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
