# Generated by Django 2.2.6 on 2019-10-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_auto_20191005_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
