# Generated by Django 2.2.6 on 2019-10-30 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_auto_20191021_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='profile',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
