# Generated by Django 2.2.6 on 2019-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0006_auto_20191007_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
