# Generated by Django 2.2.6 on 2019-10-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0008_auto_20191008_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Leo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Santos', max_length=150),
            preserve_default=False,
        ),
    ]
